# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: instascrape
subtitle: Instagram scraping for humans
logo: "/images/logo.png"
teaser: /images/fulllogo.png
email: chris@christophergreening.com
name: &name Chris Greening
description: >- # this means to ignore newlines until "baseurl:"
 instascrape is a powerful, lightweight Python library for scraping Instagram data
 with no configurations necessary! It is designed with flexibility and developer
 productivity in mind so you can stop wasting valuable time preparing Instagram
 data and just start analyzing it.
baseurl: "/instascrape/" # the subpath of your site, e.g. /blog
url: "https://chris-greening.github.io/instascrape/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ChrisGreening2
github_username:  chris-greening
repository: "chris-greening/instascrape"
# Build settings
markdown: kramdown
# theme: minima
remote_theme: "mmistakes/minimal-mistakes@4.21.0"
minimal_mistakes_skin: "dark"
plugins:
  - jekyll-feed
  - jekyll-include-cache

# Social Sharing
twitter:
  username         : &twitter "ChrisGreening2"

author: 
  name             : *name
  avatar           : "images/chris-greening.jpg"
  bio              : "Always a dev, sometimes a photographer"
  location         : "New York"
  email            : "chris@christophergreening.com"
  github           : "chris-greening"
  linkedin         : "chris-greening-646411139"
  twitter          : *twitter


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

defaults: 
  # _posts
  - scope: 
      path: ""
      type: posts
    values:
      layout: single 
      author_profile: true 
      read_time: true 
      comments: true 
      share: true 
      related: true 
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

include: ["_pages"]

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/ChrisGreening2"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/chris-greening"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/chris-greening-646411139/"